[theme]
base="light"
primaryColor="#007BFF"
backgroundColor="#F8F9FA"
secondaryBackgroundColor="#E9ECEF"
textColor="#212529"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 10
