[theme]
primaryColor = "#27AE60"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E232D"
textColor = "#FFFFFF"
font = "sans serif"

[server]
maxUploadSize = 10
address = "0.0.0.0"
port = 8501
